terms:
  API:
    "Application Programming Interface - a set of protocols and tools for building software applications"
  
  CLI:
    "Command Line Interface - a text-based interface for interacting with software"
  
  MCP:
    "Model Context Protocol - a protocol for providing context to AI models"
  
  REST:
    "Representational State Transfer - an architectural style for designing web services"
  
  SDK:
    "Software Development Kit - a collection of tools and libraries for developing software"
  
  YAML:
    "YAML Ain't Markup Language - a human-readable data serialization format"
  
  JSON:
    "JavaScript Object Notation - a lightweight data interchange format"
  
  Git:
    "A distributed version control system for tracking changes in source code"
  
  Repository:
    "A storage location for software packages or source code"
  
  Endpoint:
    "A specific URL or URI where an API can be accessed"

